### PR TITLE
Add live hot reloading via react-hot-loader

### PR DESCRIPTION
**Pull request by gaearon**
Not sure if you want to bring this in, but it gives you hot reloading without unmounting / losing state.

I had to extract functions you close over in `getInitialStateStream` but other than that it works perfect: **you can edit animations midflight** and they change without unmounting.

I didn't need to extract closures in click handlers because obviously those handlers can be replaced themselves just fine.

Feels very chilling actually.

I changed:

* `npm run watch` to work through Webpack dev server & hot loader
* `npm run build` to build `out.js` with Webpack as well

### CODE REVIEW

**Comment by gaearon** [comment]
Updated to work with existing commands & spit out `out.js` for GH pages.

**Comment by chenglou** [comment]
Oh man I totally didn't see this PR. Sorry but I've just pushed an important change (see recent diff) and this doesn't merge anymore.

Also, this is super cool lol. We should do https://www.youtube.com/watch?v=gtXpOD6jFls with this, but our method is editor-independent! Meanwhile though, I really want to keep the repo as focused as possible on the API. This is some really unstable stuff and I don't want to accommodate for anything else for now.

Sorry again, but I'll close the PR for now. In the future I'll open up an issue when I feel the time's right and I'll ping you if you're still down =).

**Comment by gaearon** [comment]
Yeah sure :-)
I will try to keep my fork up to date to keep playing with this!

**Comment by gaearon** [comment]
I updated my fork with the latest changes if anyone fancy a try.

**Pull request closed without merging**
